

module.exports = {
    SEND_GAME_SESSION: 1,
    SESSION_REQUEST: 2,
    CLIENT_SESSION_ESTABLISHED: 3,
    SESSION_NOT_EXIST: 4,
    CHECK_ONGOING_GAME: 5,
    HAS_ONGOING_GAME: 6,
    INIT_GAME_LOBBY: 7,
    JOIN_GAME: 8,
    PLAYER_JOINED: 9,
    PLAYER_DISCONNECT: 10,
    START_GAME: 11,
    GAME_STARTED: 12,
    INIT_GAME_CANVAS: 13,
    MOVE_PLAYER: 14,
    PLAYER_SHOOTING: 15,
    MOVE_ASTEROID: 16,
    ASTEROID_DESTROYED: 17,
    NEW_ENEMY_ATTACK: 18
};